services:
  - type: web
    name: yookassa-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
